services:
  # Test Environment (常に起動)
  rugby-board-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app:delegated
      - test_node_modules:/app/node_modules
      - ./coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:unit
    networks:
      - rugby-board-network

  # Development Environment (引数でプロファイル指定)
  rugby-board-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5527:5527"
    volumes:
      - .:/app:delegated
      - dev_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FIREBASE_TOKEN=${FIREBASE_TOKEN:-}
    stdin_open: true
    tty: true
    networks:
      - rugby-board-network
    profiles:
      - dev

  # Production Environment (引数でプロファイル指定)
  rugby-board-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - rugby-board-network
    profiles:
      - prod

  # Firebase Emulator (統合テスト用 - オプション)
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    ports:
      - "4000:4000" # Emulator Suite UI
      - "9099:9099" # Authentication
      - "8080:8080" # Firestore
    volumes:
      - ./firebase.json:/home/node/firebase.json:ro
      - ./firestore-data:/home/node/firestore-data
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN:-dummy}
    command: firebase emulators:start --only auth,firestore
    networks:
      - rugby-board-network
    profiles:
      - integration

volumes:
  dev_node_modules:
  test_node_modules:

networks:
  rugby-board-network:
    driver: bridge
