services:
  rugby-board-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - rugby-board-network

networks:
  rugby-board-network:
    driver: bridge
