services:
  rugby-board-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5527:5527"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - rugby-board-network

networks:
  rugby-board-network:
    driver: bridge
